### PR TITLE
Add support for Dovecot LMTP service

### PR DESCRIPTION
**Pull request by ganto**
Add option to configure Dovecot LMTP service and adjust local
  Postfix to deliver mail via Dovecot LMTP.

### CODE REVIEW

**Comment by drybjed** [comment]
Looks good. This will add `debops.postfix` as hard dependency but I suppose there's nothing we can do about it.

**Comment by ganto** [comment]
Thanks for merging... Will need to clean up the macros a bit before it's ready for another release.

Hmn, is postfix a hard dependency even there are the conditions?

**Comment by drybjed** [comment]
What I mean is, role will be evaluated and skipped.

I'm not sure how `ferm` behaves in that case though, I didn't notice two `ferm` runs so it might be broken, and using default installation process won't catch that since `common.yml` configured `ferm` already. So it might be that right now when `dovecot` role runs, only `ferm` rules from `postfix` role (since it's earlier) are executed.

That probably could be solved by adding `allow_duplicates: True` to `ferm` role.

**Comment by ganto** [comment]
Hmn, I don't think I understand what you mean here. Will be in IRC later.

**Pull request merged**
